chore: upgrade git packages

diff --git a/dot_fzf/executable_uninstall b/dot_fzf/executable_uninstall
--- a/dot_fzf/executable_uninstall
+++ b/dot_fzf/executable_uninstall
@@ -51,13 +51,8 @@ remove() {
 }
 
 remove_line() {
-  src=$(readlink "$1")
-  if [ $? -eq 0 ]; then
-    echo "Remove from $1 ($src):"
-  else
-    src=$1
-    echo "Remove from $1:"
-  fi
+  src=$1
+  echo "Remove from $1:"
 
   shift
   line_no=1
@@ -75,8 +70,9 @@ remove_line() {
     echo    "  - Line #$line_no: $content"
     [ "$content" = "$1" ] || ask "    - Remove?"
     if [ $? -eq 0 ]; then
-      awk -v n=$line_no 'NR == n {next} {print}' "$src" > "$src.bak" &&
-        mv "$src.bak" "$src" || break
+      temp=$(mktemp)
+      awk -v n=$line_no 'NR == n {next} {print}' "$src" > "$temp" &&
+        cat "$temp" > "$src" && rm -f "$temp" || break
       echo  "      - Removed"
     else
       echo  "      - Skipped"
@@ -104,10 +100,10 @@ if [ -d "${fish_dir}/functions" ]; then
   remove "${fish_dir}/functions/fzf.fish"
   remove "${fish_dir}/functions/fzf_key_bindings.fish"
 
-  if [ "$(ls -A "${fish_dir}/functions")" ]; then
-    echo "Can't delete non-empty directory: \"${fish_dir}/functions\""
-  else
+  if [ -z "$(ls -A "${fish_dir}/functions")" ]; then
     rmdir "${fish_dir}/functions"
+  else
+    echo "Can't delete non-empty directory: \"${fish_dir}/functions\""
   fi
 fi
 
